### ISSUE TITLE
logfile append

### ISSUE THREAD

**Issue by MyNewBie** [CytraL/HClient#27]
I have an idea for client , in logfile we cant save all the history ! save history is limit and history deleted after each run client and save new , can make it unlimited for save history logfile ? I mean save history all the time and don't remove it after run client , I play teeworlds for 5 years and I have to many memories form this game and I want save it all the time , I see some guys they have history from 2010 to 2015 in them logfiles , I ask them how ? they told me we change source for save history forever.

**Comment by CytraL** [comment]
Thx for report! it will be included/fixed in next release ;)

**Comment by MyNewBie** [comment]
I got error : 

src/base/system.c(298) : error C2143: syntax error : missing ';' before 'type'
src/base/system.c(299) : error C2065: 'aBuf' : undeclared identifier
src/base/system.c(299) : warning C4047: 'function' : 'char *' differs in levels
of indirection from 'int'
src/base/system.c(299) : warning C4024: 'str_format' : different types for forma
l and actual parameter 1
src/base/system.c(299) : error C2065: 'aBuf' : undeclared identifier
src/base/system.c(300) : error C2065: 'aBuf' : undeclared identifier
src/base/system.c(300) : warning C4022: 'io_write' : pointer mismatch for actual
 parameter 2
src/base/system.c(300) : error C2065: 'aBuf' : undeclared identifier
src/base/system.c(300) : warning C4047: 'function' : 'const char *' differs in l
evels of indirection from 'int'
src/base/system.c(300) : warning C4024: 'str_length' : different types for forma
l and actual parameter 1
bam.exe: 'objs/base/system.obj' error 2
bam.exe: error: a build step failed
Press any key to continue . . .

**Comment by CytraL** [comment]
https://github.com/CytraL/HClient/blob/master/src/base/system.c#L298

Umm... Errors don't match what is uploaded.... try download sources again and tell me if  still doesn't work

**Comment by CytraL** [comment]
Tested on windows and no problems detected... try downloading again a clean source :)

**Comment by MyNewBie** [comment]
maybe this is problem I used it in ddnet source !

**Comment by CytraL** [comment]
If you like implement it on DDNet see:
- https://github.com/CytraL/HClient/blob/master/src/base/system.c [Lines: 134, 306]
- https://github.com/CytraL/HClient/blob/master/src/base/system.h#L185

**Comment by MyNewBie** [comment]
yes sure I know it and I did this but as you know I got them errors :)

**Comment by CytraL** [comment]
Paste here https://gist.github.com/ the "dbg_logger_file" method...

**Comment by MyNewBie** [comment]
done

**Comment by CytraL** [comment]
tell me the URL for see it :D

**Comment by MyNewBie** [comment]
https://gist.github.com/MyNewBie/b12f02610eb93b87f7ac

**Comment by CytraL** [comment]
best copy all system.c :P xD

**Comment by MyNewBie** [comment]
:D ok https://gist.github.com/MyNewBie/3287c8d304c84db63358

**Comment by MyNewBie** [comment]
https://github.com/CytraL/HClient/blob/master/src/base/system.h#L281
not like ddnet , is it problem ?

**Comment by MyNewBie** [comment]
https://github.com/CytraL/HClient/blob/master/src/base/system.c#L281
ddnet haven't this like hclient, is it problem ?

**Comment by CytraL** [comment]
umm no.. the errors its that:
src/base/system.c(298) : error C2143: syntax error : missing ';' before 'type'

but i see all ";" xD

**Comment by MyNewBie** [comment]
so any idea :D ?

**Comment by CytraL** [comment]
I comment here: https://gist.github.com/MyNewBie/3287c8d304c84db63358

**Comment by MyNewBie** [comment]
compiler done but we removed the question not solve the problem :D !?

**Comment by CytraL** [comment]
xDDDD yes but is a strange error... :/ i see that ddrace source changes some stuff from vanilla source api and perhaps there is the error... need changes in the calls :S

**Comment by MyNewBie** [comment]
ok so im waiting for your next commit xD
great work

**Comment by CytraL** [comment]
you are using ddnet source from release or trunk? i like try compile it by myself

and thx ;)

**Comment by MyNewBie** [comment]
ddnet source from release

**Comment by CytraL** [comment]
Ummm i can compile with the changes...

**Comment by MyNewBie** [comment]
you mean after remove L139 til L145 ? yes I can compile too , but I like with start date.

**Comment by CytraL** [comment]
i can with start date ;)

**Comment by MyNewBie** [comment]
o_O

**Comment by MyNewBie** [comment]
I use visual studio 2010 and bam. maybe promble is this ?

**Comment by CytraL** [comment]
ummmm maybe... i use mingw (gcc)

**Comment by MyNewBie** [comment]
lol no I found that problem :D just move char aBuf[128]; above char aDate[20]; now compiler done :D

**Comment by MyNewBie** [comment]
but question is : why ? :D !!!!!!

**Comment by CytraL** [comment]
ohhh now that you say it true!! its C not C++!! (and VS uses C compiler) hahahaha in ANSI C you need declare all variables at the beginning

**Comment by MyNewBie** [comment]
oOps :D that's the point  xD now solved tnx a lot  you great guy

**Comment by CytraL** [comment]
You welcome, thank you too i fix it :)
