### ISSUE TITLE
Mac OS X Compiling errors

### ISSUE THREAD

**Issue by jxsl13** [CytraL/HClient#31]
https://drive.google.com/file/d/0BzuLf5KEoaAZOWdCdkQyQTZvRzQ/view?usp=sharing

didnt want to simply copy the raw text, because mac seems to show it in a more readable way, maybe it helps finding the errors faster.

Hope you could somehow fix them so that compiling becomes easier for people with no coding knowlegde :)

Greets.

**Comment by CytraL** [comment]
Thx for report! I will try fix all errors... (more of them is that "redefinition")

And wow.... wavpack have 1000000000000000000000000000000000000000000 warnings!! O_o

**Comment by CytraL** [comment]
Fixed here: https://github.com/teeworlds/teeworlds/issues/1334

**Comment by CytraL** [comment]
@jxsl13  Is this fixed?

**Comment by jxsl13** [comment]
https://docs.google.com/document/d/1fp03BzkN1t4hOL9tM45vRCg9mDhlOJ89xMyjQUM_pYI/edit?usp=sharing

only copied the errors

thx for your work :)

**Comment by CytraL** [comment]
Now best? xDD

Thank you for feedback! ;)

**Comment by CytraL** [comment]
Changed status to zombie because anybody report  if continues or not with problem

**Comment by jxsl13** [comment]
http://pastebin.com/ZgEESV2V

**Comment by CytraL** [comment]
thx for report... i you can try with this bam.lua: https://gist.github.com/CytraL/cfd1d17600a44ccafe18

**Comment by jxsl13** [comment]
http://pastebin.com/SfkQ3jWu

**Comment by H-M-H** [comment]
see my pull request #52 
@jxsl13 you need this to tell your compiler where to find all X11 stuff: https://github.com/H-M-H/HClient/blob/mac/bam.lua#L180 however, that won't be your only problem :D

**Comment by jxsl13** [comment]
used you branch, got a few errors :)

http://pastebin.com/TV70FWvb

**Comment by H-M-H** [comment]
seems your version of SDL is outdated, try this: http://meandmark.com/blog/2011/11/sdl-opengl-typedef-redefinition-error-on-mac-os-x-10-7/

**Comment by CytraL** [comment]
Fixed thx H-M-H ;)
