### ISSUE TITLE
Segfault on play demo from command line

### ISSUE THREAD

**Issue by nheir** [CytraL/HClient#48]
`./teeworld -c "play demofile.demo"`
Program received signal SIGSEGV, Segmentation fault
backtrack:
#0  0x00007ffff62191c2 in vfprintf () from /usr/lib/libc.so.6
#1  0x00007ffff6241e29 in vsnprintf () from /usr/lib/libc.so.6
#2  0x000000000047d9d5 in str_format (buffer=buffer@entry=0x7fffffffd8c0 "/home/riri/.teeworlds/", buffer_size=buffer_size@entry=512, format=format@entry=0x4f57a2 "%s%s%s") at src/base/system.c:1732
#3  0x0000000000475b64 in GetPath (BufferSize=512, pBuffer=0x7fffffffd8c0 "/home/riri/.teeworlds/", pDir=0x80000093fab9 <error: Cannot access memory at address 0x80000093fab9>, Type=0, 
    this=0x956ce0) at src/engine/shared/storage.cpp:246
#4  CStorage::OpenFile (this=0x956ce0, pFilename=0x80000093fab9 <error: Cannot access memory at address 0x80000093fab9>, Flags=1, Type=<optimized out>, 
    pBuffer=0x7fffffffd8c0 "/home/riri/.teeworlds/", BufferSize=512) at src/engine/shared/storage.cpp:272
#5  0x0000000000479436 in CDemoPlayer::Load (this=this@entry=0x7ffff2194350, pStorage=0x956ce0, pConsole=<optimized out>, 
    pFilename=pFilename@entry=0x80000093fab9 <error: Cannot access memory at address 0x80000093fab9>, StorageType=StorageType@entry=-1) at src/engine/shared/demo.cpp:584
#6  0x00000000004897b1 in CClient::DemoPlayer_Play (this=0x7ffff218b030, pFilename=0x80000093fab9 <error: Cannot access memory at address 0x80000093fab9>, StorageType=-1)
    at src/engine/client/client.cpp:2224
#7  0x000000000046ca4b in CConsole::StoreCommands (this=0x92f8e0, Store=<optimized out>) at src/engine/shared/console.cpp:886
#8  0x000000000048bcbd in CClient::Run (this=this@entry=0x7ffff218b030) at src/engine/client/client.cpp:1926
#9  0x000000000040679e in main (argc=3, argv=0x7fffffffdf18) at src/engine/client/client.cpp:2499

**Comment by CytraL** [comment]
Thx for report... it's a funny bug... xD seems that the error starts in other site fuuuu....
